"""empty message

Revision ID: 69555ea6f5be
Revises: 
Create Date: 2022-04-23 12:10:07.050291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69555ea6f5be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setup')
    # ### end Alembic commands ###
